cleaning_costmap:
   global_frame: map
   robot_base_frame: robot1/base_link
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   resolution: 0.1
   transform_tolerance: 1.0
   inflation_radius: 0.15
   map_type: costmap

cleaning_plan_nodehandle:   
   size_of_cell: 21
   grid_covered_value: 200
