global_costmap:
   global_frame: map
   robot_base_frame: robot1/base_link
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: true
   rolling_window: false
   resolution: 0.1
   transform_tolerance: 1.0
   map_type: costmap
